### ISSUE TITLE
mkrc without hooks

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/rcm#102]
I don't see any reason for `mkrc` to run hooks and would prefer it didn't. I'd also be OK with adding `-k`/`-K` support so I can disable them myself.

**Comment by spwhitt** [comment]
I'd like to second this. It's counterintuitive that mkrc runs pre-up and post-up, it's not useful (you could just run rcup manually), and it's not documented.

Particularly problematic is when passing multiple files to mkrc. In this case, the hooks get run once for each file. For instance: mkrc .weechat/*.conf runs the hooks 13 times.

**Comment by mike-burns** [comment]
I'd be interested in a pull request that updates the man page to describe existing behavior, or a PR to change that behavior but adds `-k` and `-K` to force hooks.
