### ISSUE TITLE
Using .dotfiles/rcrc

### ISSUE THREAD

**Issue by hugelgupf** [thoughtbot/rcm#103]
When I first clone my .dotfiles repo, I have to symlink .rcrc to .dotfiles/rcrc manually. That's a bit of a hassle, why not look at .dotfiles/rcrc (or, well, $DOTFILES_DIR/rcrc) when .rcrc does not exist? 

Edit: I suppose the tricky part here is supposed to be the -d option, which is not processed until after rcrc is needed.

**Comment by docwhat** [comment]
I just use this [`hooks/pre-up/rcm-configure`](https://github.com/docwhat/dotfiles/blob/master/hooks/pre-up/rcm-configure):

```
#!/bin/bash

set -eu

pushd "$(dirname "$0")" > /dev/null
cd ../..
dotfiles_dir="$(pwd)"
popd > /dev/null

if [ ! -f "${HOME}/.rcrc" ]; then
  echo "INFO: Installing default ~/.rcrc file" 1>&2
  cp "${dotfiles_dir}/rcrc.example" "${HOME}/.rcrc"
fi
```

Which copies [`rcrc.example`](https://github.com/docwhat/dotfiles/blob/master/rcrc.example) to `~/.rcrc`.

**Comment by sudomateo** [comment]
Given a `${HOME}/.dotfiles/rcrc` file I use:

```
$ cd
$ rcup rcrc
$ rcup
```
