### ISSUE TITLE
Add to official homebrew formulae? 

### ISSUE THREAD

**Issue by bcomnes** [thoughtbot/rcm#110]
Is there a reason why it was decided to support installation through homebrew using a tap instead of adding formula to the official formula repo?  If not, I would be happy to start that process to get it added.

**Comment by bcomnes** [comment]
Sorry, meant to follow up on this a while ago.  I ended up needing more cross platform (*sigh* windows) support so I ended up going with an ansible solution instead so I'm not using `rcm` any longer and probably wouldn't be good at maintaining an formula over in the homebrew repo.

**Comment by mike-burns** [comment]
Unfortunate, but thanks for the update.
