### ISSUE TITLE
list all managed files with lsrc

### ISSUE THREAD

**Issue by fgarcia** [thoughtbot/rcm#111]
Currently rc files that only exist within a tag like `.dotfiles/tag-git/gitconfig` are not listed with a normal `lsrc` run

That was the default behavior I expected, and cannot find an option to just list all managed files, not just the ones listed at the root of `.dotfiles`

**Comment by mike-burns** [comment]
I'd look at a pull request that adds this functionality, though I'd also like to know the use case.
