### ISSUE TITLE
Should I be using mkrc -S ~/.emacs.d or do it on individual files?

### ISSUE THREAD

**Issue by bishopmatthew** [thoughtbot/rcm#124]
...like for my `~/.emacs.d/init.el`, `~/.emacs.d/Cask`, etc. 

Also, not sure if I'm understanding correctly but when I run `mkrc -S ~/.emacs.d` I get:
```
Moving...
Linking...
ln: /Users/matthewbbishop/.emacs.d/: No such file or directory
```

What I was expecting was for .emacs.d to be moved into .dotfiles and a symlink from ~/ to there to be created. It moves the directory, but no symlink is created.

**Comment by mike-burns** [comment]
@bishopmatthew can you run with `-vvv` and paste that output, too, please?

**Comment by mike-burns** [comment]
Closing due to reporter time out.
