### ISSUE TITLE
man pages not installed correctly on FreeBSD

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/rcm#131]
Installing rcm on FreeBSD via the usual `configure`, `make`, `make install` incantation puts the manual pages in `/usr/local/share/man`, which isn't on the default `MANPATH`.

According to hier(7), `/usr/local` should follow the same layout as `/usr`, with some exceptions, including:

> the man directory (directly under `local/` rather than under `local/share/`)

It doesn't look like there's anything out of the ordinary in rcm's `man/Makefile.am`, so this is probably autotools' fault. Two days into using FreeBSD and I'm already finding reasons to get annoyed at GNU software.

**Comment by georgebrock** [comment]
After a little Googling:

* This can be worked around with `./configure --mandir=/usr/local/man`
* rcm isn't the only program to have this problem (e.g. http://lists.freebsd.org/pipermail/freebsd-questions/2012-November/246029.html and https://github.com/ewxrjk/rsbackup/issues/3)

It might be that the fix for this is a documentation change, or a FreeBSD port, or just that I learn my new OS better before opening issues on the software I want to use.

**Comment by mike-burns** [comment]
```sh
~% env MANPATH= manpath 
/usr/share/man:/usr/local/man:/usr/share/openssl/man:/usr/local/lib/perl5/site_perl/man:/usr/local/lib/perl5/5.18/perl/man
```

This absolutely needs to be fixed, and I think a port is the best solution -- though if you find an autoconf solution that Just Works, I'd be even happier.

**Comment by mike-burns** [comment]
Some ports/pkgng notes in #31. It'd be best to make this a real part of the FBSD ports tree and not something that is built from this project's Makefile.

**Comment by mike-burns** [comment]
And indeed, bsd.port.mk sets `--mandir` explicitly (I'm on 9.3-STABLE; YMMV).

**Comment by mike-burns** [comment]
I'm going to close this: this would be resolved by someone taking on as a FreeBSD porter for the project, or by someone mentioning instructions on dealing with the man path during the `configure` step.
