### ISSUE TITLE
Curlable/wgettable installation script

### ISSUE THREAD

**Issue by langri-sha** [thoughtbot/rcm#137]
I'm sure something like this would require overlooking a lot of the technical minutiae involved with managing user configuration files correctly, but I would thoroughly appreciate if I can, on a completely clean box, pipe some script and get `rcm` installed for my user with `thoughtbot/dotfiles` installed as my base, à la `robbyrussell/oh-my-zsh` style.

In a nutshell, I would want it to be possible to take a newly created user in a utterly new system, `curl https://thoughtbot.github.io/~scripts/foo.sh | sh` and receive instant gratification.

**Comment by mike-burns** [comment]
There is no way this will ever happen. Use your package manager instead.
