### ISSUE TITLE
Whole Folders

### ISSUE THREAD

**Issue by SeeThruHead** [thoughtbot/rcm#139]
Hello. I've got a fish functions folder that I would like to symlink with rcm.

When I do `mkrc -S -t fish ~/.config/fish/functions` everything seems to be working fine
i can even `rcdn` and `rcup -t fish` and it looks like everything is working

However when the entire fish folder is removed and I do `rcup` rcm links files individually instead of the folder. Is there a way to set this?

**Comment by mike-burns** [comment]
Yes, use `SYMLINK_DIRS`, as documented in rcrc(5).

**Comment by SeeThruHead** [comment]
I'm having some trouble figuring out the globbing patters, "functions" works, but how would I specify only functions inside my tag-fish/config/fish/ directory.

I've tried all sorts of different combinations and haven't come across one that works.

**Comment by mike-burns** [comment]
I don't fully understand, but the equivalent of the `-S` you showed above should be:

```
SYMLINK_DIRS=config/fish/functions
```

Run `lsrc -v` to see more verbose ouput.

**Comment by SeeThruHead** [comment]
WIth 
`SYMLINK_DIRS="config/fish/functions"`
I get
`Recurring on /Users/STH/.config/fish/functions`
however `SYMLINK_DIRS="functions"`
gives me
`/Users/STH/.config/fish/functions:/Users/STH/.dotfiles/tag-fish/config/fish/functions`

Not really sure what I'm doing wrong here, I think I've followed the documentation for exclude patterns from lsrc.
