### ISSUE TITLE
The tutorial is not a tutorial

### ISSUE THREAD

**Issue by offero** [thoughtbot/rcm#140]
This project sounds interesting, but I don't know how to use it or how it will benefit me.

**Comment by Koronen** [comment]
Have a look at [the tutorial](http://thoughtbot.github.io/rcm/rcm.7.html). It should help answer your questions.

**Comment by mike-burns** [comment]
@offero if you figure out how to use it and how it will benefit you, please submit a pull request to improve the documentation. I love doc improvements. A lot.
