### ISSUE TITLE
Is there still an Arch package?

### ISSUE THREAD

**Issue by steeeve** [thoughtbot/rcm#143]
The AUR link seems dead?

https://aur.archlinux.org/packages/rcm-git/

**Comment by mike-burns** [comment]
Bummer. Can you contribute one in its place, @steeeve ?

**Comment by thiagowfx** [comment]
Yes, I just re-created it. See it here: https://aur4.archlinux.org/packages/rcm/

**Comment by steeeve** [comment]
Thanks @thiagowfx!

Did you follow the instructions in [DEVELOPERS.md](https://github.com/thoughtbot/rcm/blob/master/DEVELOPERS.md)? I didn't have any success, but then I'm completely green to Arch.

Or do the instructions need updating?

**Comment by mike-burns** [comment]
Thanks @thiagowfx ! I'll update the README when I next get a chance (or you could submit a PR).

**Comment by thiagowfx** [comment]
Hi there. I didn't need to follow these instructions because I reused the previous existing package (then slightly improved it). But I will read them as soon as I have time and see if it needs any updates.

**Comment by mike-burns** [comment]
This seems to be taken care of now.
