### ISSUE TITLE
error when use mkrc to a dotfile which is already known by rcm

### ISSUE THREAD

**Issue by wty21cn** [thoughtbot/rcm#144]
when I accidentally use mkrc to a dotfile rcm already known, the problem comes, rcm will generate a symlink in ~/.dotfiles/ which point to itself, and delete the original dotfile in~/.dotfiles/ and delete the original symlink in ~/ as well, then I lost the dotfile. how can I solve this problem?

**Comment by mike-burns** [comment]
Thanks for reporting this. I have not looked into it yet, but this seems straight-forward to reproduce.

**Comment by benjaminwood** [comment]
I can confirm this, as I just had it happen myself. It's a dangerous bug for those that are new to dotfile management (of which I am one). Fortunately I did have a backup of this file, so it wasn't lost forever. It did give me a moment of fright, though.

I think it'd be simple to fix. If the target file is a symlink, abort. I can't think of a situation where you'd want to move a symlink into your .dotfiles directory.

Thoughts on this? I'm happy to contribute a fix if I know I'm headed in the right direction.

**Comment by mike-burns** [comment]
@benjaminwood yup agreed: if the target is a symlink, abort.

**Comment by mat-m** [comment]
It also fails when you stop to add a folder to SYMLINK_DIRS.
I ran rcup and it linked the files against themselves, since the old link on the folder was not removed.

**Comment by nkgm** [comment]
This is extremely dangerous as it's trivially easy to trigger. Just run `mkrc .zshrc` twice and your `.zshrc` is gone for good.

**Comment by mat-m** [comment]
@mike-burns : If many files are given, and one is a symlink, do we abort the whole command or just exclude symlinks from the command ?

**Comment by mike-burns** [comment]
Ideally abort the whole command. But I'd also be fine with whichever is easiest to develop.

**Comment by mat-m** [comment]
I will go for global abort. I prefer to send a message 

> Clean your mess before launching the command.

rather than
> We will try to work on as many as we can even if it is messed up.

**Comment by mike-burns** [comment]
Merged. Thank you!
