### ISSUE TITLE
Handling deleted files

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/rcm#147]
There may not be a way to do this cleanly, but occasionally I've deleted local customizations in my dotfiles after they've been pulled into the base thoughtbot dotfiles. When those files are deleted, there are dead symlinks left behind that point to now-missing files. I'm trying to think of a way to prune these symlinks in a way that's both safe and reliable.

**Comment by mike-burns** [comment]
I'd love to solve this. See #104 for prior thoughts on it.

**Comment by geoffharcourt** [comment]
Nice, there's clearly already been a lot of thought here. My reaction after mulling this over is to advocate for something with less power than the manifest proposal, but something that safely prunes symlinks, especially ones that are nested in sub-dot-directories like `.vim` and `.zsh`. Here's what I'm thinking:

1. Make a list of the root directory and any directories referenced in the user's dotfiles repositories. [For me](https://github.com/geoffharcourt/dotfiles) that would be `.bin`, `.bundle`, `.rbenv`, `.vim`, `.zsh` as well as most of the tree structure underneath `.vim` and `.zsh`.
2. Walk each of those folders top-level contents and look for broken symlinks. 
3. Delete the symlinks.

I want to be sure that the effort outweighs the complexity required to perform those tasks. The advantage of just hunting for broken symlinks is that we wouldn't be risking deleted files specified in a migration that have since been replaced by an outside file. If we're only deleting dead symlinks we're unlikely to break anything that wasn't already broken. The disadvantage would be the process of assembling a list of the directories involved seems like it would be messy.

**Comment by mike-burns** [comment]
How about a flag to rcdn(1) that only drops broken symlinks?

**Comment by georgebrock** [comment]
How about a new rcck(1) command? I'm thinking of something like fsck(1) that can identify problems, and optionally repair them.

A separate command might be more flexible than an rcdn(1) flag, e.g. it could be invoked at the end of rcup(1).

**Comment by geoffharcourt** [comment]
@mike-burns @georgebrock I started fleshing out `rcck(1)` in https://github.com/thoughtbot/rcm/pull/167. Would like to get your feedback on the approach before I start work on tests, a man page, and anything else that might be needed to produce a complete solution.

**Comment by geoffharcourt** [comment]
This approach would not handle non-dotted broken symlinks directly under `$HOME` or broken symlinks in non-dotted folders, but I think the potential slowness of traversing every directory under `$HOME` is not worth the cost.
