### ISSUE TITLE
Hooks are not run in the directory they are contained but file generation would benefit from it

### ISSUE THREAD

**Issue by jkniiv** [thoughtbot/rcm#148]
Currently hooks are not executed with a current working directory being where they are situated. Instead it seems the cwd is set to the target directory for symlinked dotfiles, aka `$HOME`. However, this makes it hard to implement a simple makefile-driven generation of dotfiles from templates as one doesn't know for sure which one of `$DOTFILES_DIRS` the hooks belong to.

Case in point. I have the following in a pre-up hook (`pre-up/10-make-files.sh`):
```shell
#!/bin/sh
test -r ../../Makefile && make -C ../..
```
With my changes to `rcm.sh.in` (will be submitting pull requests) the above will start a build of my dotfiles (only bashrc so far) by way of a simple awk-based macro preprocessor called `m5` (a play on `m4`). The following is then my Makefile:
```make
DOTFILE = bashrc
DEPS = $(wildcard *.sh.m5)

M5 = m5
M5FLAGS = -dp '`' -sp '%'

.PHONY : all clean

all : $(DOTFILE)

$(DOTFILE) : $(DOTFILE).m5 $(DEPS)
	$(M5) $(M5FLAGS) $< > $@

clean :
	rm -f $(DOTFILE) a.awk
```
So it is my humble opinion that the hooks mechanism would benefit from setting the current working directory somewhere predictable and especially in the context of the dotfiles they are embedded with. To that end one can either simply change `share/rcm.sh.in` to call `find(1)` with the `-execdir` action instead of `-exec` -- or -- considering POSIX compliance alternatively use the `-print` action with `xargs(1)` plus a shell oneliner. The latter is technically less secure but as one shouldn't trust someone else's dotfiles (and hence hooks) naively anyway without a review, this is pretty much a moot point.

**Comment by mike-burns** [comment]
Merged your fixes. Thank you!
