### ISSUE TITLE
Solaris 10 lacks readlink(1), also neither the default grep(1) nor diff(1) have a `-q` option

### ISSUE THREAD

**Issue by jkniiv** [thoughtbot/rcm#151]
On Solaris I get the following kind of output from `make check` even with `LOG_COMPILER = cram --shell=/bin/ksh` set:
```
====================================
   rcm 1.2.4: test/test-suite.log
====================================

# TOTAL: 31
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  28
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: lsrc-dotfiles-dirs.t
==========================

!
--- lsrc-dotfiles-dirs.t
+++ lsrc-dotfiles-dirs.t.err
@@ -9,5 +9,15 @@
   > touch .third-dotfiles/t-example
 
   $ lsrc -d .second-dotfiles -d .third-dotfiles
-  /*/.s-example:/*/.second-dotfiles/s-example (glob)
-  /*/.t-example:/*/.third-dotfiles/t-example (glob)
+  grep: illegal option -- q
+  Usage: grep -hblcnsviw pattern file . . .
+  /export/home/vagrant/src/rcm-1.2.4/test/../bin/lsrc[340]: .second-dotfiles:  not found
+  /export/home/vagrant/src/rcm-1.2.4/test/../bin/lsrc[357]: .second-dotfiles:  not found
+  grep: illegal option -- q
+  Usage: grep -hblcnsviw pattern file . . .
+  grep: illegal option -- q
+  Usage: grep -hblcnsviw pattern file . . .
+  /export/home/vagrant/src/rcm-1.2.4/test/../bin/lsrc[340]: .third-dotfiles:  not found
+  /export/home/vagrant/src/rcm-1.2.4/test/../bin/lsrc[357]: .third-dotfiles:  not found
+  grep: illegal option -- q
+  Usage: grep -hblcnsviw pattern file . . .

# Ran 1 tests, 0 skipped, 1 failed.
[...]
```
This means that the default `grep` on Solaris is rather handicapped. One could use `/usr/xpg4/bin/grep` but then we should have to test for its existence. Easiest I think is to avoid the `-q` option altogether and just redirect stdout to /dev/null (don't know if stderr should be too). Same thing with `diff(1)` although this time it's POSIX that drops the option.

Also the test suite's `helper.sh` calls `readlink(1)` but Solaris 10 doesn't seem to carry one unless one is willing to install GNU coreutils. However, Perl's `Cwd` has `realpath()` which is a symbolic link resolver on steroids. If we can accept this dependency, a one-liner is all we need. Considering that Perl5 (even >5.8) is widely distributed even on older systems, this doesn't feel so bad (to me at least).

**Comment by otommod** [comment]
`grep -q` is [POSIX](http://pubs.opengroup.org/onlinepubs/009604499/utilities/grep.html) as far as I can tell.

**Comment by jkniiv** [comment]
To paraphrase a well-known saying: POSIX is already here – it's just not very evenly distributed. ;)  The question is, do we want to support real systems (say, AIX, HP-UX and Solaris – in *addition* to Linux+POSIX) out there or some idealized targets only? Frankly, in my opinion, there are times for either approaches. It really depends on the nature of our software. I think RCM benefits from being available as widely as possible. After all, its *raison d'etre* is to help system admins and developers to carry their dotfiles with them out in the real world – the world of *NIX shell prompts, that is.

**Comment by mike-burns** [comment]
The PR is merged. Thank you for this, and I agree: RCM should run on as many real-world systems as possible.
