### ISSUE TITLE
Test suite depends on a non-Bourne shell like Bash or Ksh

### ISSUE THREAD

**Issue by jkniiv** [thoughtbot/rcm#153]
On Solaris 10 I can't let the Cram test suite run with the default shell, i.e. /bin/sh, or I get a lot of failed tests. However if I apply the patch below (+ #152 for completeness) on for instance the tarball dist (generated by `make distcheck`), everything works just fine.
```diff
diff -urP rcm-1.2.4/test/Makefile.in rcm-1.2.4-modified/test/Makefile.in
--- rcm-1.2.4/test/Makefile.in	2015-09-06 14:53:32.000000000 +0500
+++ rcm-1.2.4-modified/test/Makefile.in	2015-09-07 10:52:18.119544000 +0500
@@ -419,7 +419,7 @@
 
 dist_check_SCRIPTS = $(TESTS)
 dist_check_DATA = helper.sh
-LOG_COMPILER = cram
+LOG_COMPILER = cram --shell=/bin/ksh
 all: all-am
 
 .SUFFIXES:
```
Frankly I don't quite know how to proceed. Most POSIX targets seem to have an alternative shell in addition to `/bin/sh` -- either (pd)ksh or bash -- so we may have reached the point of diminishing returns if we go with rewriting the tests in pure Bourne shell language (after all, if you can install Python/pip/Cram for the tests, surely you are able to install a more modern shell, too). Also I'm not sure if Cram generates some shell scripts, too. For a Python project it seems rather intimidating to delve into. That leaves us with ensuring that the best shell for the job is employed. Maybe it's as simple as modifying `LOG_COMPILER` like above but in `Makefile.am`. Of course we'd then use something like `@SHELL@` instead of mere `/bin/ksh`.

**Comment by mike-burns** [comment]
The test suite has third-party dependencies (it now has a Perl dependency now, for example). That's fine. If someone is willing to run the test suite, they're willing to install third party tools. What's important is that the final product only depends on POSIX.

Solaris /bin/sh is a nightmare that we skip. See:

https://github.com/thoughtbot/rcm/blob/master/configure.ac#L8-L15
https://github.com/thoughtbot/rcm/blob/master/bin/lsrc.in#L1

I'm going to close this for now. Thanks for bringing it up.
