### ISSUE TITLE
Please provide package for Ubuntu 15.04 (Vivid Vervet)

### ISSUE THREAD

**Issue by yuriihabrusiev** [thoughtbot/rcm#159]
Can't install `rcm` from PPA because package for Vivid is missing.

**Comment by mike-burns** [comment]
Ping @Frost .

**Comment by Frost** [comment]
Ah. I'll take care of that. I just noticed that there is no package for 15.10 either, so I'll just fix that as well.

**Comment by alobaid** [comment]
Tell then just use the Debian-based it works fine for both 15.05 and 15.10

**Comment by Frost** [comment]
@yuriihabrusiev rcm-1.2.3 is now available in the PPA for both 15.04 (Vivid) and 15.10 (Wily).

**Comment by mike-burns** [comment]
Thank you, @Frost !

**Comment by yuriihabrusiev** [comment]
Thanks, guys!
