### ISSUE TITLE
Fix manual installation steps

### ISSUE THREAD

**Issue by samvv** [thoughtbot/rcm#160]
When downloading the latest [release](https://github.com/thoughtbot/rcm/releases/tag/v1.2.3); when doing `./configure`, the following error occurs:
    
    ./configure: No such file or directory

What should be the correct command if we assume I'm doing the manual installation?

Also, when running `./autogen.sh`, it hangs on the following lines, so I wasn't able to generate it myself:

    man/Makefile.am:3: warning: shell git config --get remote.origin.url: non-POSIX variable name
    man/Makefile.am:3: (probably a GNU make extension)
    (reading log message from standard input)

**Comment by mike-burns** [comment]
That release page was generated automatically and I have no idea what it means or why it links to those files. I didn't make those tarballs, and they aren't signed by my private key.

Use this:  https://thoughtbot.github.io/rcm/dist/rcm-1.2.3.tar.gz

**Comment by samvv** [comment]
Ooh right! Strange …

Anyways; thanks for the link.
