### ISSUE TITLE
Release 1.2.4 package?

### ISSUE THREAD

**Issue by mganjoo** [thoughtbot/rcm#161]
The latest release package seems to be 1.2.3: https://thoughtbot.github.io/rcm/dist/rcm-1.2.3.tar.gz

Seems like the 1.2.4 release has been out for a while now -- could the dist folder be updated with a package for that version? That would allow the homebrew formula for rcm to be updated: https://github.com/thoughtbot/homebrew-formulae/blob/master/Formula/rcm.rb

**Comment by hugelgupf** [comment]
Loads of features have been added and tons of bugs have been fixed since May 2014. I keep having to pull from master instead of using the packages because I use newer features. It's time to release a new package. +1

**Comment by mike-burns** [comment]
I never actually released 1.2.4. But I'm actually going to release 1.3.0. I've done this today:

1. Merged most PRs.
2. Closed some finished issues.
3. Bumped the version in `configure.ac`.
4. Made a tarball.
5. Verified it on OpenBSD.
6.. Emailed known package maintainers with the tarball, so they could try it.
7. Asked some OS X-using friends to try it on OS X.

Once I hear back from the GNU and OS X contingent, I'll push this out.

Thank you for your patience!

**Comment by mike-burns** [comment]
1.3.0 is out.
