### ISSUE TITLE
Tests hang

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/rcm#168]
When I run the test suite at a801c4c58902cae7b835d890487edc39bd7da142 with `make check` on OS X 10.11 (El Capitan) with zsh, several of the tests pass, and then the suite appears to get hung up while running `mkrc-simple-output.t`. An empty log file is generated for that test, and the suite hangs for minutes with no indication of progress.

**Comment by geoffharcourt** [comment]
```
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
PASS: test/lsrc-dotfiles-dirs.t
PASS: test/lsrc-excludes.t
PASS: test/lsrc-hostname.t
PASS: test/lsrc-sigils.t
PASS: test/lsrc.t
PASS: test/lsrc-symlink-dirs.t
PASS: test/lsrc-tags.t
PASS: test/lsrc-usage.t
PASS: test/lsrc-undotted.t
PASS: test/lsrc-host-tags-default.t
PASS: test/mkrc-alternate-dotfiles-dir.t
PASS: test/mkrc-copy-file.t
PASS: test/mkrc-host-file.t
PASS: test/mkrc-hostname.t
```

**Comment by geoffharcourt** [comment]
I get the same problem when running the tests under `sh`.

**Comment by mike-burns** [comment]
If you add:

```sh
  $ set -x
```

to the second line of `test/mkrc-simple-output.t` and run that:

```sh
env TESTS=test/mkrc-simple-output.t make -e check
```

It should fail; does `test/mkrc-simple-output.t.log` illuminate where it's hanging?

**Comment by geoffharcourt** [comment]
Unfortunately I get a similar result. The log file is created, but it blank. The test produces no output and doesn't terminate.

**Comment by mike-burns** [comment]
Wild. How about, with that `set -x` moved up to the very first line:

```sh
cd test
cram -v mkrc-simple-output.t
```

**Comment by geoffharcourt** [comment]
With line 1 of the test being `set -x` I get this output:

```
~/github/thoughtbot/rcm/test master* ⇣
❯ cram -v mkrc-simple-output.t
mkrc-simple-output.t:
```

Very weird. When I run these commands with other tests the output is what I would expect (finishes immediately, outputs a summary of the test run).
