### ISSUE TITLE
rcdn: "Cannot remove /home: Permission denied"

### ISSUE THREAD

**Issue by kylecook80** [thoughtbot/rcm#169]
I ran rcdn to remove my dotfiles from my home directory, whenever this above error displayed. Nothing was deleted thankfully, but the fact that this even ran scared me to death. WHY was this command even attempted to be run?! I ran this on CentOS 6.

**Comment by mike-burns** [comment]
Glad to hear that your permissions stopped this from happening.

Can you post the output of `lsrc -vv`?

**Comment by kylecook80** [comment]
https://gist.github.com/kylecook80/04ed734f4a201a93eb37

**Comment by mike-burns** [comment]
Interesting. Can I see your .rcrc file, if you have one (which I think you do)?

**Comment by kylecook80** [comment]
I actually do not have an .rcrc file, which is curious since it is referenced a number of times there...

**Comment by mike-burns** [comment]
That is all quite surprising. You're right; on a second reading, there is no .rcrc (and it looks like there's a small bug when dealing with empty directories). I'll have to create a test setup locally -- glad to see you've published your dotfiles, I'll try with those.

Thanks for reporting this.

**Comment by kylecook80** [comment]
Awesome. Glad I could help!

**Comment by mike-burns** [comment]
Here's an update:

rcdn(1) will remove the dotfile and then attempt to remove the parent directory, if it is empty. This is to handle e.g. `.irssi/config` -- it will remove both `config` and `.irssi`.

Here's the code in question: https://github.com/thoughtbot/rcm/blob/master/bin/rcdn.in#L14-L15

It's sending errors to `/dev/null`, which raises the question: why are you seeing an error?

And also, why is it going all the way up to `/home`?

I'll keep looking at your logs for clues. Which OS are you on?

**Comment by mike-burns** [comment]
It was too aggressively recurring up the filesystem. The latest commit (a68804713a6cb9eb96278df597fd0b4fefc36598) fixes this.

Thanks again for reporting it!

**Comment by kylecook80** [comment]
Fantastic! Thanks for the fix!
