### ISSUE TITLE
Add macports instructions to readme

### ISSUE THREAD

**Issue by casey** [thoughtbot/rcm#171]
rcm is available in macports, so it would be great to mention it in the readme for people who use it.

Thanks!

**Comment by mike-burns** [comment]
Can you submit a PR? I have no idea what MacPorts users need to know to use it.

**Comment by casey** [comment]
Opened a PR!

**Comment by mike-burns** [comment]
Wonderful. Closing this, and I'll merge the PR next time I get a chance.
