### ISSUE TITLE
Add support for tag, host hooks

### ISSUE THREAD

**Issue by langri-sha** [thoughtbot/rcm#173]
I have certain tags that require cloning repositories, building sources and retrieving large static assets, but unfortunately I have to collocate the `pre-up`, `post-up` hooks in the dotfiles directory hooks and have them execute even though I may not be requiring these tags in the environment at all. 

For example, imagine a `pre-up` hook for `tag-gnome` where you fetch your favorite fonts, desktop backgrounds, shell extensions, etc. I mostly use RCM from within terminal environments, but everything I would require to provision `tag-gnome` gets executed anyway.

As a workaround, I can choose to not install any tags at all and configure `RCRC` to point to a configuration that tells RCM to treat each tag directory as a dotfiles directory and introduce `tag-foo/hooks` to all the tags. While this does work, it feels like a hack.

**Comment by mike-burns** [comment]
To clarify, you're proposing `tag-gnome/hooks/pre-up`?

**Comment by langri-sha** [comment]
Yes, to introduce `pre-up` and `post-up` hooks for tags and hosts.

**Comment by mike-burns** [comment]
Sounds like something I'd merge.

If you want to submit a pull request:

- clone the repo
- follow https://github.com/thoughtbot/rcm/blob/master/CONTRIBUTING.md
- make sure the test suite passes
- add a new test (see the very bottom of CONTRIBUTING.md)
- make the change. It will be in this range: https://github.com/thoughtbot/rcm/blob/master/share/rcm.sh.in#L119-L140

My guess on the change is that you can leverage the existing call to find(1) such that it searches `$dotfiles_dir/hooks/$when-$direction`, `$dotfiles_dir/host-$hostname/hooks/$when-$direction`, and `$dotfiles_dir/tag-foo/$when-$direction` for each tag (the tags part is a little tricky).

---

I don't leave feature request issues open, but let me know if you have questions about where to go from here.

**Comment by langri-sha** [comment]
I avoided looking at the sources like the plague, but appears to be less scary than I thought. Thanks a lot for the pointers!

**Comment by VMatrix1900** [comment]
@langri-sha Are you working on this feature?
