### ISSUE TITLE
Packages for Ubuntu 16.04 / Xenial 

### ISSUE THREAD

**Issue by IvanAnishchuk** [thoughtbot/rcm#178]
It would be beneficial to have packages in PPA built for upcoming Ubuntu 16.04. It's the next LTS release and I suspect many will rush to upgrade from 14.04. Packages built for Wily seem to be working ok so I don't suspect any great changes required. Thank you.

**Comment by Koronen** [comment]
Ping @Frost.

**Comment by Frost** [comment]
Thanks for the mention. I'll try to do fix this during the week.

**Comment by Frost** [comment]
@IvanAnishchuk rcm 1.2.3 should now be available for xenial.

I'll try to get around to push 1.3.0 to the PPA in a while. It's been too long.

**Comment by atzorvas** [comment]
@Frost any updates about the 1.3.0 release in the PPA?
thanks!

**Comment by Frost** [comment]
@atzorvas Sorry for the loooooooong delay. 1.3.0 should  be available now.

**Comment by Frost** [comment]
This issue can probably be closed now. Ping @mike-burns, for instance.

**Comment by mike-burns** [comment]
Thank you for taking care of this, too, Frost!
