### ISSUE TITLE
SHA1 is used for signatures in ubuntu ppa

### ISSUE THREAD

**Issue by IvanAnishchuk** [thoughtbot/rcm#179]
After an update, apt started to throw this warning:

`W: http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu/dists/xenial/InRelease: Signature by key 4E9A5EF6BD18E32A513B691C4609D1E5ECA538E6 uses weak digest algorithm (SHA1)`

[This wiki page](https://wiki.debian.org/Teams/Apt/Sha1Removal) provides some details how to fix it. There's enough time before it becomes critical (Jan 2017), just please do it with next release.

**Comment by IvanAnishchuk** [comment]
Ping @Frost , I suppose.

**Comment by Frost** [comment]
@IvanAnishchuk Yes, that would be me. Thanks for the notification.

**Comment by Frost** [comment]
Hi @IvanAnishchuk, is this still the case with the newer packages (rcm 1.3.1)?

**Comment by Frost** [comment]
I have verified that the source packages uploaded to the PPA for rcm 1.3.1 all contain a `Checksums-Sha256` entry, so I believe this issue can be closed.

Ping @mike-burns
