### ISSUE TITLE
Hooks per tag

### ISSUE THREAD

**Issue by jsok** [thoughtbot/rcm#180]
Just seeing if there is interest in supporting hooks on a per tag basis? The global hooks directory is useful but often a hook is only necessary if a certain tag is enabled.

The directory layout would be similar but allow a nested `hooks` directory under each tag, i.e.:

`.dotfiles/tag-*/hooks/pre-up` and `.dotfiles/tag-*/hooks/post-up`, or `.dotfiles/tag-*/hooks/pre-up/*` and `.dotfiles/tag-*/hooks/post-up/*`

**Comment by mike-burns** [comment]
Yup, I'd consider it. I don't have a use for it -- the existing hooks can check for the existence of files and act accordingly as needed. But if you have a solid use case and your implementation is of low complexity, I'd merge it.
