### ISSUE TITLE
How to undo a mkrc command

### ISSUE THREAD

**Issue by wassimk** [thoughtbot/rcm#182]
I've done a `mkrc file` to get something into my dotfiles but now I want to undo that. Is there an opposite to `mkrc`. I've read through the man pages a couple of times and I just can't seem to find it.

**Comment by mike-burns** [comment]
There is not,no. We're not opposed to such a thing -- if you write such a script, I'd gladly add it to the rcm suite -- but no such script exists.

So for now:

```sh
rm .foo
mv .dotfiles/foo .foo
```
