### ISSUE TITLE
Fedora 24 installation fails

### ISSUE THREAD

**Issue by orenyk** [thoughtbot/rcm#184]
Hi, I'm trying to install RCM on Fedora 24 through DNF but it looks like the COPR repository isn't set up yet to work with that version (I believe pinging @supervacuo would be appropriate based on #176). I'll probably proceed with a manual installation unless this is fairly quick fix, thanks!

**EDIT** Here's what I'm seeing:

```
$ sudo dnf install rcm
Failed to synchronize cache for repo 'seeitcoming-rcm', disabling.
Last metadata expiration check: 0:13:49 ago on Sun Jun 26 13:01:12 2016.
No package rcm available.
Error: Unable to find a match.
```

**Comment by supervacuo** [comment]
I've rebuilt for F24 (haven't updated the package itself yet); try it now?

**Comment by orenyk** [comment]
Thanks! I'll try to install it again tomorrow and let you know if it works.

**Comment by orenyk** [comment]
Worked great, thanks!
