### ISSUE TITLE
mkrc should use relative paths in symlinks

### ISSUE THREAD

**Issue by martinp26** [thoughtbot/rcm#185]
This would allow easy synchronization between different machines and would be robust against moving the home directory to a different place, changing user names, or mounting it in a different place.

**Comment by mike-burns** [comment]
Quite the list of edge cases there!

I'm not opposed to reviewing a diff on this. You'll want to look at the `handle_file` function in `bin/rcup.in`, especially the call to `link_file`.

Though looking at it now, the absolute path originates in `lsrc`; look at `handle_file` in `bin/lsrc.in` to see how it constructs the destination file name.
