### ISSUE TITLE
rcup hooks execute in random order

### ISSUE THREAD

**Issue by TheLonelyGhost** [thoughtbot/rcm#188]
Using [my dotfiles](https://github.com/thelonelyghost/dotfiles) (forked off of the [official thoughtbot dotfiles](https://github.com/thoughtbot/dotfiles) repo) with `rcm` is nice. I started taking advantage of the pre- and post-hooks to install packages on a once-off, idempotent basis. The problem is they run out of order.

```
hooks/pre-up
├── 1_os_specific
├── 2_ruby_version_changer
├── 3_ruby
├── 4_python_pip
├── 7_gems
├── 7_go
├── 7_node
└── 7_python
```

I've narrowed this down to a streaming issue with `find`, where it fails to sort the files it finds in the appropriate hook directory before executing it, thereby working around an assumption that it executes in any particular order. In my case, `hooks/pre-up/4_python_pip` executes before `hooks/pre-up/1_os_specific`, then `hooks/pre-up/7_node` executes.

My preference is to treat these in a priority order similar to init.d scripts in certain linux distributions. In my case, I cannot install go dependencies (`hooks/pre-up/7_go`) without first installing the system packages (`hooks/pre-up/1_os_specific`) which contain the `go-lang` package.

Pull request to follow.

**Comment by mike-burns** [comment]
Merged as bc0d5b63f6c4762b7d39fb32b525f977015ff4b3, thank you!
