### ISSUE TITLE
Packages for Ubuntu 16.10 / yakkety

### ISSUE THREAD

**Issue by oopsfoo** [thoughtbot/rcm#189]
Please update PPA
thank you @Frost

**Comment by stewarttylerr** [comment]
@Frost Any update on this?

**Comment by Frost** [comment]
@stewarttylerr 1.3.0 should be available from the PPA by now :smile:

**Comment by stewarttylerr** [comment]
Beautiful, thank you!

**Comment by Frost** [comment]
This issue can probably be closed now. Ping @mike-burns, for instance.

**Comment by mike-burns** [comment]
Thank you for taking care of this, Frost!
