### ISSUE TITLE
Packages for Fedora 25

### ISSUE THREAD

**Issue by Frost** [thoughtbot/rcm#191]
Fedora 25 has been released, and the linked [copr repository](https://copr.fedorainfracloud.org/coprs/seeitcoming/rcm/) in the README does not yet supply packages for it.

**Comment by Frost** [comment]
@mike-burns I think this can be closed now. There are packages for Fedoras 22-26 now, even though it's only 1.2.3 so far.

**Comment by mike-burns** [comment]
Thank you!
