### ISSUE TITLE
rcup creates superfluous directories for dotfiles with spaces

### ISSUE THREAD

**Issue by RobertAudi** [thoughtbot/rcm#197]
This is related to #135 which was closed by #193. But One bug still remains and it's related to `xargs` in [bin/rcup.in#L150](https://github.com/thoughtbot/rcm/blob/147a7b6/bin/rcup.in#L150) and possibly elsewhere.

For example, this will create the directory `/Users/rob/Library/Application`:

```
$ dirname "/Users/rob/Library/Application Support/MailMate/Resources/KeyBindings/0x2a.plist" | xargs mkdir -p
```

The problem is that `xargs` doesn't respect quoting. I believe the issue can be resolved using the `-d` flag with `xargs` but it's not available on OS X, which makes this solution not portable.

**Comment by fgtham** [comment]
Another solution might be:

```
printf "%s" "$(dirname "$dest")" | xargs -0 $MKDIR -p
```

**Comment by fgtham** [comment]
Or just drop `xargs`. The `-0` flag is not portable as well:

```
destdir="$(dirname "$dest")"
$MKDIR -p "$destdir"
```
