### ISSUE TITLE
Installation on a Debian system

### ISSUE THREAD

**Issue by davilera** [thoughtbot/rcm#199]
According to your `readme.md`, to install `rcm` on a Debian-based system we need to add the `apt-key` from:

`https://apt.thoughtbot.com/thoughtbot_apt.gpg.key`

However, its real location is:

`https://apt.thoughtbot.com/thoughtbot.gpg.key`

**Comment by Koronen** [comment]
#195 addresses this issue.

**Comment by davilera** [comment]
Yup, you're absolutely right. Should we close #199, then?
