### ISSUE TITLE
Vim: Warning when using rcup

### ISSUE THREAD

**Issue by alobaid** [thoughtbot/rcm#204]
I keep getting 
Vim: Warning: Input is not from a terminal
when using rcup command 
on ubuntu 16.10 4.8.0-39

**Comment by mike-burns** [comment]
This is a problem with your hooks. Check those.

If you're using the thoughtbot dotfiles, see this commit and its comments: https://github.com/thoughtbot/dotfiles/commit/99a18f6dbe99929769f28ad089cc39992d05951c
