### ISSUE TITLE
.rcmignore file

### ISSUE THREAD

**Issue by devth** [thoughtbot/rcm#207]
Instead of having to specify which files to ignore with `-x` `rcm` should support a `.rcmignore` file or similar, the same way `.gitignore` works.

**Comment by mike-burns** [comment]
Previously discussed on #86.

When you open your pull request, I will be interested in this discussion: we already have `EXCLUDES` and `INCLUDES` in rcrc(5); what does an additional rc file get us?

**Comment by devth** [comment]
> When you open your pull request

a little presumptuous :)

EXCLUDES wfm. I missed this when searching through the issues. Thanks!
