### ISSUE TITLE
[question] Symlinking files that do not belong in the root directory

### ISSUE THREAD

**Issue by benjamreynolds** [thoughtbot/rcm#208]
I have a use case where I keep the configuration for my [Übersicht](https://github.com/felixhageloh/uebersicht) widgets, (namely menubar replacement) in my dotfiles repository. [This](https://github.com/benjamreynolds/dotfiles/tree/master/nerdbar.widget) directory needs to be symlinked to `~/Library/Application Support/Ubersicht/widgets/nerdbar.widget`. I didnt find anything obvious in the documentation that supports this kind of link. Is there something I am missing or is this use case not currently supported with rcm?

**Comment by mike-burns** [comment]
Is that something you could use rcrc(5)'s `UNDOTTED` option/rcup(1)'s `-U` option for?

**Comment by benjamreynolds** [comment]
Do you mean storing the configuration in something like... `.dotfiles/Library/Application Support/Ubersicht/widgets/nerdbar.widget` and declaring the `Library` folder as `UNDOTTED`? Wouldn't that symlink my entire `~/Library` folder, leading to some pretty unpredictable behavior with my whole system? (considering `~/Library` holds all sorts things)

**Comment by mike-burns** [comment]
Could combine that with `COPY_ALWAYS`/`-C` to avoid the symlink.

Also, only files are symlinked, not directories (unless you use `SYMLINK_DIRS`/`-S`).
