### ISSUE TITLE
Updating to rcm 1.3.1 results in strange terminal state requiring reset

### ISSUE THREAD

**Issue by pmkhoa** [thoughtbot/rcm#209]
Related issue can be found here: https://github.com/thoughtbot/dotfiles/issues/516
After updating to rcm 1.3.1, running `rcup` causing this:
```
Vim: Warning: Input is not from a terminal
Vim: Caught deadly signal ABRT
Vim: Finished.
```

Current environment:
-  vim: 8.0
-  iTerm: 3.0.14
- zsh: 5.0.8

**Comment by mike-burns** [comment]
This is a dotfiles bug. (Really it's a vim bug.)
