### ISSUE TITLE
Symlinks for dotted files in subdirectory, .e.g ~/.dotfiles/zsh/.zshrc

### ISSUE THREAD

**Issue by jschaf** [thoughtbot/rcm#211]
I can't figure out how to make ~/.dotfiles/zsh/.zshrc link to ~/.zsh/.zshrc.

rcup ignores dotted files in subdirectories.  Is there a way to change this behavior?

**Comment by mike-burns** [comment]
There is no way to keep the dot. Feel free to put any hidden files in there with a dot, and they will be ignored by rcm.

**Comment by jschaf** [comment]
For future finders of this issue, here was my workaround to keep zshrc, zshenv and friends inside ~/.dotfiles/zsh

**~/.dotfiles/hooks/post-up/010-link-zsh-startup**

```zsh
#!/bin/zsh

# RCM ignores dotted files in subdirectories.  This behavior is expected.  See
# https://github.com/thoughtbot/rcm/issues/211.  Unfortunately, it means we
# can't rely on RCM to setup ZDOTDIR correctly.  For example, the following
# files won't get symlinked:
#
# ~/.dotfiles/zsh/.zshrc - Not symlinked
# ~/.dotfiles/zsh/.zshenv - Not symlinked
#
# If we use no dot on zshrc, RCM symlinks it like so:
#
# ~/.dotfiles/zsh/zshrc - ~/.zsh/zshrc
# ~/.dotfiles/zsh/zshenv - ~/.zsh/zshenv
#
# ZSH uses $ZDOTDIR/.zshrc, so zsh won't find it in this case.

function rcm-link-zsh-startup-files() {
  local files=($@)
  for file in $files; do
    local dotfile_location="$HOME/.dotfiles/zsh/$file"
    local zdotdir_location="$HOME/.zsh/$file"
    if [[ "$(readlink $zdotdir_location)" == "$dotfile_location" ]]; then
      continue
    elif [[ -f "$zdotdir_location" ]]; then
      local message="ERROR: $zdotdir_location already exists and is not linked "
      message+="to ~/.dotfiles/zsh."
      print "$message"
      return 1
    else
      if [[ -f "$dotfile_location" ]]; then
        ln -s "$dotfile_location" "$zdotdir_location"
      fi
    fi
  done
}

rcm-link-zsh-startup-files .zshrc .zshenv .zprofile .zlogin .zlogout
```

**Comment by mike-burns** [comment]
Ah, `ZDOTDIR`. Got it.

How about:

`~/.rcrc`:

```sh
SYMLINK_DIRS="zsh"
```

?

**Comment by jschaf** [comment]
Yes, that was my initial solution.  There were a couple downsides:

* .zsh_history, cache and other data ends up in your repo which you need to add to .gitignore.
* I have a work dotfiles that installs some zsh scripts.  The symlink approach prevents that from working.  This was the reason I did the post-hook approach.

**Comment by CHE1RON** [comment]
Anyone running into `not a valid identifier`, rename the function to something without hyphens, eg `zdotdirSymlink` 😅
