### ISSUE TITLE
Tests are not parallel-safe

### ISSUE THREAD

**Issue by mgorny** [thoughtbot/rcm#212]
I've noticed that the tests can fail when run with `make -jN check` (N > 1). This at least applied to rcup/rcdn tests because they all use the same path `/tmp/test` path, so if multiple tests run in parallel, they might simultaneously use the same file and e.g. one test may remove it when other expects it to exist.

Besides, it'd be a much better idea to use safe filenames for tests. Otherwise you might up accidentally removing user's files if he just happened to use `/tmp/test` for something. Usually in shell this is done via calling `mktemp -d` to create a unique temporary directory in which you can safely put your files.

**Comment by mike-burns** [comment]
Sounds great, I'd definitely merge a patch that fixes this.
