### ISSUE TITLE
Cannot use `~` in `DOTFILES_DIRS` in `rcrc`

### ISSUE THREAD

**Issue by rmeritz** [thoughtbot/rcm#218]
I was not able to use `DOTFILES_DIR="~/my-dots"`. I got no output from `lsrc`. But when I switch to `/home/username/my-dots` it worked.

**Comment by mike-burns** [comment]
This is a great idea!

If you want to implement this, you'll probably want to do that around https://github.com/thoughtbot/rcm/blob/master/bin/lsrc.in#L320 .

I don't know the most portable tool to expand `~` -- I see that readlink(1) on OpenBSD has a `-f` flag that does this -- but the easiest thing to do might be to `s/~/$HOME`.
