### ISSUE TITLE
Update `rcm` copr for Fedora 27

### ISSUE THREAD

**Issue by jsmestad** [thoughtbot/rcm#224]
Now that Fedora 27 is out, the copr repo needs to be updated to support the latest version.

**Comment by supervacuo** [comment]
Done! :confetti_ball: 

`sudo dnf copr enable seeitcoming/rcm`
`sudo dnf install rcm`

Feel free to ping me directly in future

**Comment by rrocchi** [comment]
Hi Carl, is there any chance that you can do the same for Fedora 28?

**Comment by supervacuo** [comment]
Yes! Building now ☺

**Comment by supervacuo** [comment]
Done! @mike-burns I think this issue can be closed?

**Comment by mike-burns** [comment]
Thank you for taking care of this!
