### ISSUE TITLE
Packages for Ubuntu 18.10 / cosmic

### ISSUE THREAD

**Issue by kbussell** [thoughtbot/rcm#239]
Please update PPA to include the packages for 18.10. Thanks!

**Comment by toddboom** [comment]
Bumping this because I would also love updated packages for 19.04 which will go GA next week. Thank you!

**Comment by Frost** [comment]
Hi! I am the package maintainer for the Ubuntu PPA. Sorry for not seeing this issue earlier, but I don't generally look around here a lot without someone mentioning me when they see there's some issue with the PPA.

I uploaded a package for 18.10 to the PPA several months ago, and for 19.04 and later versions, `rcm` is available through the `universe` package repo, and I will therefore stop publishing to the PPA for newer versions of Ubuntu. See #247 for some more info on this.
