### ISSUE TITLE
lsrc -t TAG lists files above tag directory

### ISSUE THREAD

**Issue by Tank-Missile** [thoughtbot/rcm#243]
For instance, if you have a rcrc file and a tag-Test directory in the same directory, using lsrc -t Test will print all files under tag-Test and rcrc.

**Comment by mat-m** [comment]
Current behavior is:

Using -t TAG **adds** files from tag to list. `lsrc` ignores them by default. You can ` | grep tag-TEST` to limit output.
`lsrc` is first a backend command, and its default behavior cannot be changed.
But I think we miss  introspection commands, something like `rcup --dry-run` and `lsrc --check-existing`

**Comment by mike-burns** [comment]
I'd love a `rcup -N` (dry run) flag, and until then lsrc is passable. Not great, but it gets the job done.

It might make sense to have `lsrc -T some-tag` print _only_ the files under `some-tag`. That could reduce some confusion.

In the meantime, this is working as expected so I'm going to close it.
