### ISSUE TITLE
keys expired

### ISSUE THREAD

**Issue by gilcot** [thoughtbot/rcm#249]
Hello,

Currently, an `apt-get update` is throwing GPG expiration errors
```
W: GPG error: https://apt.thoughtbot.com stable Release: The following signature were invalid: KEYEXPIRIED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 KEYEXPIRED 1571249459 
```
My source file is as follow:
```
deb https://apt.thoughoutbot.com/debian/ stable main
```

**Comment by gilcot** [comment]
I didn't mention this:
```
apt-key list | grep -A 1 expired
pub    4096R/BE7FEF18 2014-10-17 [expired: 2019-10-16]
uid                   thoughtbot Security Team <security@thoughtbot.com>
```
Thanks.

**Comment by todeveni** [comment]
There's a new subkey. Just update the current key.

`apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 EC478DAB713A4BC3`

**Comment by todeveni** [comment]
(and that's for Debian repo), don't know if Ubuntu repo uses the same key.

**Comment by gilcot** [comment]
Thanks @todeveni  ; that works for me 

As said @bramswenson  ; I just used the official link as instructed by the documentations.

**Comment by mike-burns** [comment]
As others pointed out, we have new subkeys and have extended the expiration on the master key. You can download the key here: https://thoughtbot.com/thoughtbot.asc

You are right that the `apt.thoughtbot.com` key is incorrect. The only times we have problems with `apt.thoughtbot.com` is when @tabfugnic is offline, so: hey @tabfugnic , when you're back, can you adjust the key on `apt.thoughtbot.com` please?

**Comment by stratigos** [comment]
I fixed this for my machine today, and I am using Ubuntu 18.04

First, I downloaded the key as linked by @mike-burns above: https://thoughtbot.com/thoughtbot.asc

Then I imported the new key with the following command: 

* :computer:  `sudo apt-key add - < ~/Downloads/thoughtbot.asc`
* :memo: you may need to change the path to the file to the download location on your system

Then when I `sudo apt-get update`, the error is gone, and the update process completes with success :slightly_smiling_face:

**Comment by gilcot** [comment]
As https://thoughtbot.com/thoughtbot.asc is fine, I may close the issue. However, documentation should be updated as it points to https://thoughtbot.com/thoughtbot.key

**Comment by tabfugnic** [comment]
Hey all, I've since updated the apt key on https://apt.thoughtbot.com/thoughtbot.gpg.key. It is now in line with expiration date of the parent key. You can continue to use the thoughtbot.com key or the key in the documentation.
