### ISSUE TITLE
Question about Makefile

### ISSUE THREAD

**Issue by mat-m** [thoughtbot/rcm#253]
I don't know if I made a mistake or miss any instructions, but I ahad an issue when running the tests.
The lib is built in `./share/rcm.sh` and scripts are searching `../share/rcm/rcm.sh` which has one more level.

I temporarily defined a symlink `./share/rcm`, but can't the file be generated on target folder directly ?

**Comment by mike-burns** [comment]
Sorry, I don't see this error. Can you share the commands you're running and what the error message is?

**Comment by mat-m** [comment]
Can't reproduce with the old clone and a fresh one, closing.
