### ISSUE TITLE
mkrc and DOTFILES_DIRS

### ISSUE THREAD

**Issue by mat-m** [thoughtbot/rcm#254]
`man mkrc` gives:

> -d DIR  install dotfiles under the specified directory. This can be specified multiple times.

Since in the code we have:

```
for DOTFILES_DIR in $DOTFILES_DIRS $DEFAULT_DOTFILES_DIR; do
  break
done
```

I think we should add that:
*  The first `-d` option in the command overrides the setting in the RCRC file
*  Only the last one is used to deliver files, because the way it is coded, each further option overrides the previous one.

**Comment by eddsalkield** [comment]
`man rcm` specifies, in the _MULTIPLE DOTFILE DIRECTORIES_ section, that the behaviour of multiple dotfile directories being given in the RCRC file alongside the _-d_ flag is to go in sequence through all given directories, updating symlinks such that overlapping rc files use the first result that matches for them.

The code you're quoting is from `mkrc` which seeks to "bless" existing dotfiles into a new directory.  This is why only one dotfile directory is chosen by the code: it does not make sense to symlink a dotfile from multiple locations.  In all other rcm tools, all given directories are iterated through as per the above specification.

**Comment by mat-m** [comment]
@eddsalkield We need to update the man, at least:

* Since we break without checking for directory liveness, we may update the man to remove the multiple times sentence, which makes no sense.
* If we add a liveness check `[ -d "$DOTFILES_DIR" ]`, still update the man to tell that the first existing dir will be used.

**Comment by mat-m** [comment]
I am in favor of the existence check.

Additionally, if a `-d` option is given, it forgets about values from RCRC and default one ($HOME/.dotfiles).
If multiple -d are given, the last one wins, since mkrc will overwrite the one variable with each value.

**Comment by eddsalkield** [comment]
Excellent work on this, and sorry for not contributing further to the discussion here - playing around with rcm was rather thrown on the backburner for me! I think your implemented (and now merged) approach, including the existence check and man page update, is the best one. :smile:
