### ISSUE TITLE
mkrc creates dotfiles dir if it doesn't exist

### ISSUE THREAD

**Issue by mat-m** [thoughtbot/rcm#259]
Hello 

With the following lines, we create all folders recursively, but there is no previous check of $DOTFILES_DIR existence.

https://github.com/thoughtbot/rcm/blob/cbc346b279b5c08b281c9901b994a58eb037a60d/bin/mkrc.in#L148-L149

So, with no `-d` option, and no `.rcrc` file, if $HOME/.dotfiles doesn't exist, it is created for us.
If there is a typo in the $DOTFILES_DIR, a new folder is created.

I am in favor of expecting the $DOTFILES_DIR to already exist ?

What are your views ?

**Comment by mat-m** [comment]
Proposal: https://github.com/thoughtbot/rcm/pull/262

**Comment by mike-burns** [comment]
Hm! Good question. thinking aloud here:

- We'd need to change the rcm(7) tutorial for "quick start for empty dotfiles directories".
- My original thought was: we have to make the files under $DOTFILES_DIR, so we might as well make the directory as well.
- In practice, almost everyone has an existing dotfiles dir so they won't notice this.
- This will catch typos in `DOTFILES_DIR`/`-d` settings.
- There is a [classic race here](https://thoughtbot.com/blog/toctou), in that the directory can go missing between when we check for it and when we write to it.
- We probably have a lot of races already.

I think this change makes sense. Thank you for including it in #262.

**Comment by mat-m** [comment]
I guess we can close this one :)
