### ISSUE TITLE
Add Focal Fossa (Ubuntu 20.04) support in ppa

### ISSUE THREAD

**Issue by mat-m** [thoughtbot/rcm#264]
Hello

@Frost  Can you add focal support in the ppa, pelase ?

I have migrated to Linux Mint 20, which builds on top of Focal Fossa (20.04)

Thanks

**Comment by Koronen** [comment]
> As of Ubuntu 19.04 (Disco Dingo), rcm is now available in the Universe
> package repository (https://packages.ubuntu.com/disco/rcm).
> 
> The ppa will no longer be necessary for future versions of Ubuntu but
> will be kept around until the older releases are EOL.

https://github.com/thoughtbot/rcm/pull/247

**Comment by Frost** [comment]
Hi @mat-m. Just like @Koronen mentioned, you no longer need the ppa in order to get `rcm` on Ubuntu. I'm using it directly from the universe repo on 20.04 myself.

Here's an updated package link for 20.04: https://packages.ubuntu.com/focal/rcm

**Comment by mat-m** [comment]
Perfect. Using Mint, I did not check if rcm was available from Ubuntu universe before asking. Thanks
