### ISSUE TITLE
Getting sed issue when running rcup

### ISSUE THREAD

**Issue by jandamm** [thoughtbot/rcm#265]
I'm getting the following issue since the last release:
```
sed: 1: "s|:/Users/jan.dammshaeu ...": bad flag in substitute command: '|'
```
It happens after my hooks and before handling dirs.

I was using `gnu-sed` on my mac before, getting this message:
```
sed: -e expression #1, char 70: unknown option to `s'
```

**Comment by mike-burns** [comment]
That's surprising. Looks like you're on macOS, correct?

Do you mind sharing your home dir? `echo $HOME` should suffice.

**Comment by jandamm** [comment]
Yes, I'm running macOS.
My $HOME is `/Users/jan.dammshaeuser`

**Comment by mike-burns** [comment]
Real tricky -- I can't figure out what's gone wrong.

Do you mind adding `-vvv` to whichever command you're running. I can't tell whether your `DEST_DIR` is becoming corrupted somewhere. I hope it's not a hook ...

**Comment by jandamm** [comment]
Thanks for the feedback I've switched computers in the meantime and the error disappeared. So at least for me the issue is closed 👍
