### ISSUE TITLE
Ability to unlink a file?

### ISSUE THREAD

**Issue by ryanwood** [thoughtbot/rcm#275]
Is there a way to unlink and leave the dot files as file instead of symlink? 

I guess I'm looking for the opposite of `mkrc` which takes `~/.vimrc` and changes to a symlink to `~/.dotfiles/vimrc`. Using `rcdn vimrc` will delete the symlink which is not what I want. What I'd like to to be able to run `mkrc` in reverse so it effectively reverses the action, removing it from RCM and replacing the symlinked version with the original dotfile. 

Is that possible?

**Comment by mat-m** [comment]
Hello, here is a workaround:

```bash
cd $HOME
# Erase link
rcdn vimrc
# Create the copy
rcup -C vimrc
```

Does it work for your case ?

**Comment by ryanwood** [comment]
That's perfect. Thank you!

**Comment by mat-m** [comment]
It does not remove it from RCM, though. You need to remove the file in the dotfiles dir.
If you are using git :  `git rm ~/.dotfiles/vimrc`
