### ISSUE TITLE
Test failures on fresh clone

### ISSUE THREAD

**Issue by magikid** [thoughtbot/rcm#278]
The `test/mkrc-one-dotfile-arg.t` is failing on a fresh clone of the project because of the changes in 4fcb2b7d25354cdacf3c1efd16d4f5bd64dd55e7 adding the `-k` flag to mkrc.

**Comment by Koronen** [comment]
This was recently fixed in 3e2ac541f68673e2556d66e166e7cdcebd1ad0a2.
