### ISSUE TITLE
FAIL: test/mkrc-one-dotfile-arg.t

### ISSUE THREAD

**Issue by qrkourier** [thoughtbot/rcm#282]
Hi Mike, I'm trying to take a look at `rcup` to see if I can [add a feature](https://github.com/thoughtbot/rcm/issues/281) to submit a PR, but I ran into a test failure when I ran `make check` while following the setup instructions in `CONTRIBUTING.md` on the pristine master branch. I'm sure I'll need to solve this, and will take this opportunity to ask for a little guidance navigating the testing framework here. I'm sure I'll need to add a test for the new behavior too, if I'm able to find the source. :sweat_smile: 

```
=================================
   rcm 1.3.4: ./test-suite.log
=================================

# TOTAL: 44
# PASS:  43
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/mkrc-one-dotfile-arg.t
=================================

!
--- test/mkrc-one-dotfile-arg.t
+++ test/mkrc-one-dotfile-arg.t.err
@@ -13,7 +13,7 @@
 
   $ mkrc -d .dotfiles -d .other-dotfiles rcfile
   Only one '-d' option is allowed in mkrc.
-  Usage: mkrc [-ChSsUuVvqo] [-t TAG] [-d DIR] [-B HOSTNAME] FILES ...
+  Usage: mkrc [-ChSsUuVvqokK] [-t TAG] [-d DIR] [-B HOSTNAME] FILES ...
   see mkrc(1) and rcm(7) for more details
   [64]
 

# Ran 1 tests, 0 skipped, 1 failed.
FAIL test/mkrc-one-dotfile-arg.t (exit status: 1)

```

I'll keep poking around for a little while, but I'm still not sure

**Comment by Koronen** [comment]
This was recently fixed in 3e2ac541f68673e2556d66e166e7cdcebd1ad0a2.
