### ISSUE TITLE
Exit if pre-up exits non-zero

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/rcm#288]
I was surprised to find that when `hooks/pre-up` exits non-zero, `rcup` still proceeds.

My use case for this is related to https://github.com/thoughtbot/rcm/issues/103; basically I want to put a check in `pre-up` that fails if I've not done [this step](https://github.com/thoughtbot/rcm/issues/103#issuecomment-50179244) yet (install the `rcrc` configuration independently first). Sometimes I forget when setting up a new machine and a config-less `rcup` will do many incorrect things that are tricky to undo (since an `rcdn` afterwards _will_ see the config).

Is this a bug? If not, I'd like to submit it as a feature request 😉. If you'd like to not change default behavior, a flag to enable something like "fail on hook failures" would work for me too.

**Comment by pbrisbin** [comment]
I've drafted a PR for this [here](https://github.com/thoughtbot/rcm/pull/289). Let me know if you'd like to proceed and I'll set it ready for review.

**Comment by mike-burns** [comment]
Yeah sounds good. I'm in the mood to break some stuff, and I'm also surprised that it doesn't already work like this. Going to review the PR.

**Comment by mike-burns** [comment]
You did this in #289. Thank you!
