### ISSUE TITLE
tag-specific pre-up and post-up hooks

### ISSUE THREAD

**Issue by mgorbach** [thoughtbot/rcm#48]
I'd like a way to add a `hooks` directory to tags, so that tags can have their own `pre-up` and `post-up` hooks. Here's a use case:
I have a `vim` tag that installs my `.vimrc` file. I'd like a post-up hook that creates the .vim directory if it doesn't exist and automatically clones vundle so that I can install bundles listed in my `.vimrc` next time I start vim. I don't want a general `post-up` hook because only machines using the tag `vim` should run this particular part of the script.
Similarly, I have a `zsh` tag. I want all machines using zsh to run a post-up hook that clones and installs oh-my-zsh, if it doesn't exist.

**Comment by olalonde** [comment]
:+1:

**Comment by olalonde** [comment]
One work around for post hooks:

Put a hook script in `tag-YOURTAG/hook-YOURTAG`. `rcup` will symlink `~/.hook-YOURTAG` and add some code to the `hooks/post-up` which will source `~/.hooks-sometag` if the file exists.

**Comment by mike-burns** [comment]
This project should handle crazy complex setups with grace and ease. I would enjoy seeing a pull request for this feature.

I'm going to close this Issue for now. Thanks for bringing the idea up.
