### ISSUE TITLE
C version of lsrc

### ISSUE THREAD

**Issue by caleb** [thoughtbot/rcm#68]
I saw some talk here about making a C version of `lsrc`. So I went ahead and wrote it.

Here's the branch:

https://github.com/caleb/rcm/tree/lsrcc

It's not yet integrated with the auto* tools, so you'll have to `clang lsrc.c` it manually.

All of the features of the shell version should be included in the C version, and it's significantly faster (0.02 seconds vs 16 seconds with my admittedly big dotfiles directory).

This first version is basically a port of the APIs from the shell version to C. In the future I would be interested in cleaning up those APIs to maybe remove shell-isms, but to keep parity I decided to port the functions directly as much as possible.

I've been using this for a couple weeks now with no problems. It handles spaces, and files with asterisks in their names, etc. I used only POSIX C99 (I believe!), and have tested a slightly older version on NetBSD, FreeBSD, OpenBSD, Ubuntu, and OS X.

I would definitely do testing on the final version on those platforms if you're interested in merging.

Is this something that you'd be interested in including upstream if I finish the build system and testing?

**Comment by mike-burns** [comment]
Closing this with some sadness: I really think POSIX sh is the right thing to use for this project. Thank you very much for bringing this up and for the C re-write, @caleb .

**Comment by PaBLoX-CL** [comment]
Why?

**Comment by mike-burns** [comment]
@PaBLoX-CL simply: portability and maintainership.

- POSIX sh is everywhere; a C compiler is not. We could have rcm everywhere using package managers, but there just aren't enough people maintaining packages for all OSes. We could make use of the `-g` flag to encourage users to generate sh if they need portability, but `-g` is not powerful enough yet.
- I don't have it in me to maintain rcm as a C project.

**Comment by PaBLoX-CL** [comment]
Ah, no, I meant. If you distribute a binary, a compiler it's not needed, but I obviously understand the time problem.
