### ISSUE TITLE
user-[user]@[hostname] dir for user specific files

### ISSUE THREAD

**Issue by rominf** [thoughtbot/rcm#70]
I can handle specific configs for PCs with `host...` dir. I wish to have `user-[user]@[hostname]` directory for user files. Why do I need this? Well, I'm using `rcm` as a normal user and as a root and I cannot use `mkrc -o ~/.rcrc` recipe as root user don't uses GUI applications (and corresponding tags of course).

**Comment by mike-burns** [comment]
Thanks for bringing up this idea. I'd be interested in looking at a pull request to implement it.
