### ISSUE TITLE
Ability to package rcm within the dotfiles repository itself

### ISSUE THREAD

**Issue by gabetax** [thoughtbot/rcm#71]
Most people with existing dotfile repos handle file installation via a home-rolled make, rake, or shell script. While I love the idea of using rcm as a robust OTS framework, I don't look forward to having the additional step of installing rcm itself, _especially_ on servers where I don't have root access.

It's clear from #68 that it's a good design decision to reduce the number of dependencies within rcm. Wouldn't it be nice if we could also remove the dependency of installing rcm itself? rcm still seems pretty portable (assuming it doesn't get completely re-written in c). Is there any reason we can't bundle it -- or at a minimum, just rcup -- inside the dotfiles repo the same way people vendor ruby gems with `bundle package`?

**Comment by mike-burns** [comment]
Closing this because I hope that `-g` (starts to) solve this for people. It will need improvement, but adding it will get the ball rolling.
