### ISSUE TITLE
Generated executables are not

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/rcm#75]
After running the `autogen.sh`, `configure`, `make` incantation, I find that the generated executables under `./bin` are not executable. 

```
% ls -l bin
total 68
-rwxr-xr-x 1 patrick users  8119 Mar 31 17:43 lsrc.in*
-rw-r--r-- 1 patrick users 15038 Mar 31 17:43 Makefile
-rw-r--r-- 1 patrick users    39 Mar  6 17:26 Makefile.am
-rw-r--r-- 1 patrick users 14731 Mar 31 17:43 Makefile.in
-rwxr-xr-x 1 patrick users  1707 Mar 31 17:43 mkrc.in*
-rwxr-xr-x 1 patrick users  2261 Mar 31 17:43 rcdn.in*
-rwxr-xr-x 1 patrick users  3577 Mar 31 17:43 rcup.in*
-rw-r--r-- 1 patrick users  8881 Mar  3 12:10 tags
% make
...
% ls -l bin
total 88
-rw-r--r-- 1 patrick users  8119 Mar 31 17:50 lsrc
-rwxr-xr-x 1 patrick users  8119 Mar 31 17:43 lsrc.in*
-rw-r--r-- 1 patrick users 15038 Mar 31 17:43 Makefile
-rw-r--r-- 1 patrick users    39 Mar  6 17:26 Makefile.am
-rw-r--r-- 1 patrick users 14731 Mar 31 17:43 Makefile.in
-rw-r--r-- 1 patrick users  1707 Mar 31 17:50 mkrc
-rwxr-xr-x 1 patrick users  1707 Mar 31 17:43 mkrc.in*
-rw-r--r-- 1 patrick users  2261 Mar 31 17:50 rcdn
-rwxr-xr-x 1 patrick users  2261 Mar 31 17:43 rcdn.in*
-rw-r--r-- 1 patrick users  3577 Mar 31 17:50 rcup
-rwxr-xr-x 1 patrick users  3577 Mar 31 17:43 rcup.in*
-rw-r--r-- 1 patrick users  8881 Mar  3 12:10 tags
```

This breaks the test suite branch because the altered `$PATH` does not find them.

Looking at #72, I expected this to be because they were set as `_DATA`, not `_SCRIPTS` (the reverse of that issue), but that's not the case.

My installation seems to work, so permissions are probably set correctly when `make install` actually fires -- but the test suite requires (at least at this point) that the local files be executable too.

**Comment by mike-burns** [comment]
Yes, that is what's happening; it uses the install(1) program, which makes it executable. If you can find a way to get this locally, just let me know.
