### ISSUE TITLE
Dry run option

### ISSUE THREAD

**Issue by alanpearce** [thoughtbot/rcm#77]
I think that it would be helpful if `rcup`, `rcdn` and maybe `mkrc` accepted a `-n` option, which doesn't actually move any files, in a similar way to `rsync` and `git clean`.

I have a different layout in my dotfiles directory current, so I'd like to be able to see what would happen if I ran some commands. I've been using `lsrc`, but I'm not sure if it's the same as a hypothetical `rcup -n`, since it is a different command.

**Comment by mike-burns** [comment]
I would love a `-n` dry run flag, and would excitedly review a pull request that adds such a feature.

**Comment by PaBLoX-CL** [comment]
There's no need. `lsrc` works as a dry run.
