### ISSUE TITLE
Separate repository- and host-specific rcrc configuration options

### ISSUE THREAD

**Issue by alanpearce** [thoughtbot/rcm#78]
It seems a bit weird to have both in the same file, particularly with `EXCLUDES` vs `TAGS`.

I'm not quite sure how would be best to handle this. `.rcignore` would be a nice idea, but probably not that easy to implement and only handles `EXCLUDES`.

Alternatively, perhaps `$dotfiles/.rcrc` might be better, since it's more generic and still fits in with the idea of ignoring dotfiles.

Currently I'm working around this with an idea borrowed from `thoughtbot/dotfiles`:
```
EXCLUDES="Brewfile launchagents"
[[ -e ~/.rcrc.local ]] && source ~/.rcrc.local
```
Where .rcrc.local is a host-specific file. I'm not too fond of throwing .local files everywhere though. I might try it the other way around (i.e. `.system` instead).

**Comment by mike-burns** [comment]
If you are still interested in this, I'd look at a pull request that shows how you think this should work.
