### ISSUE TITLE
Handle non-dotted dotfiles

### ISSUE THREAD

**Issue by alinnow** [thoughtbot/rcm#79]
This is probably easier to explain by example:

Say I have `~/Library/LaunchAgents/my.plist` that I want to bless.
I run `mkrc Library/LaunchAgents/my.plist`. If I run `lsrc`, I see that `rcup` would create a link in `~/.Library/...`, which is obviously not what I want.

If you don't like the idea, at least consider throwing an error when running `mkrc` on a non-dotted file, since `rcup` cant't handle it.

**Comment by leomao10** [comment]
Noticed that this is mark as 2.1.0 milestone, and this feature is merged almost 10 months ago, wondering if there is a date for  2.1.0 release?

**Comment by mike-burns** [comment]
@leomao10 No set date, but I'd really like to get it out this month.

**Comment by leomao10** [comment]
Awesome :) Thanks a lot
