### ISSUE TITLE
Thoughts about mkrc with absolute/full paths

### ISSUE THREAD

**Issue by PaBLoX-CL** [thoughtbot/rcm#87]
Ok, this basically started since I tried to run:

```shell
~ ❯❯❯ mkrc -v /tmp/t/.foo
Moving...
'/tmp/t/.foo' -> '/home/pablo/.dotfiles//tmp/t/.foo'
Linking...
```

This came up when I tried to add the feature in thoughtbot/rcm@2e283083e6, though it's not something that was introduced there (considering the bugfixes).

So, here's the thing: what's the point in using `mkrc` in a file from the root outside the home directory? I don't think so it actually makes sense. The only use case I can came up would be trying to "backup" global configuration files (`/etc/X11/xorg.conf.d/something.conf`), but it's also a PITA since you would need special privileges.

Having a path starting with `/` it's not enough,since `/home/user/.vimrc` it's actually valid and it's run correctly through `mkrc`.

So, wouldn't be better add a handling to cover those edge cases? Maybe we could add a condition inside the case statement to see if the full path includes `$HOME` and if it's not, bail out more gracefully.

**Comment by mike-burns** [comment]
This would be a good UX improvement, and I would gladly look at a pull request that adds it.
