### ISSUE TITLE
Prefer tagged files over non-meta-files

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/rcm#94]
So if you have:

    .dotfiles/tag-freebsd/kshrc
    .dotfiles/kshrc

An `lsrc -t freebsd` would only list the `kshrc` in `.dotfiles/tag-freebsd/kshrc`.

What do people think? This is a breaking change, and I don't have feelings on it either way.

**Comment by docwhat** [comment]
@bcomnes Alas, no... host files do not override the default files. :sob:
