### ISSUE TITLE
rcup: add option for calling diff program on a conflict

### ISSUE THREAD

**Issue by rominf** [thoughtbot/rcm#95]
I update my dotfiles with `rcup` and it gives me:
```
overwrite /root/.oh-my-fish/custom/plugins/example/example.fish? [ynaq]
```
It would be nice to have one another option `d` for calling diff program `diff`, for example, or `vimdiff` depending on a line in config file (default value):
```
DIFF_PROGRAM="diff $SRC $DST"
```

To make it clear I propose to change question to:
```
overwrite $FILE? (y/n/d/a/q/? - show all options) [y]:
```

`?` should give brief explanations of options. `y` is default.

This is somehow related with #13, but it works on concrete file, not for all files.

**Comment by graham33** [comment]
The recent pull request I submitted (#132) addresses this requirement in some respects, although I didn't add support for a custom diff tool.

**Comment by mike-burns** [comment]
Closing this issue in favor of #132.
